name: Build C++ EXE
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Qt 6 install කරන ලේසිම විදිහ
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.0'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'

      # OpenCV විතරක් vcpkg හරහා install කරමු
      - name: Install OpenCV via vcpkg
        run: |
          vcpkg install opencv4:x64-windows

      - name: Configure CMake
        run: |
          cmake -B build -S . `
          -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake `
          -DVCPKG_TARGET_TRIPLET=x64-windows

      - name: Build Project
        run: cmake --build build --config Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FlashPrint-Enhancer-EXE
          path: build/Release/*.exe